{% set name = "ipymaterialui" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e5f3a06549e525603c42c2c1ecf2134970aa33277e8fe171597cf1f5c67cac18

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - ipywidgets >=7.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - ipymaterialui

about:
  home: http://github.com/maartenbreddels/ipymaterialui
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Modern form/ui elements for Jupyter Widgets'

  description: |
    Modern form/ui elements for Jupyter Widgets

extra:
  recipe-maintainers:
    - mariobuikhuizen
